apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
          expires 1d;
          add_header Cache-Control "public, no-transform";
        }

        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>John's Portfolio</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/css/styles.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="/" class="active">Home</a></li>
                    <li><a href="/modules/snake-game/">Play Snake</a></li>
                    <li><a href="/modules/news-feed/">Latest News</a></li>
                    <li><a href="#projects">Projects</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </header>
        
        <main>
            <section class="about-me section">
                <h1>Welcome to My Digital Space</h1>
                <div class="profile-container">
                    <img src="/images/profile.jpg" alt="Profile Picture" class="profile-image">
                    <div class="bio">
                        <h2>Hi, I'm John! 👋</h2>
                        <p>I'm a passionate full-stack developer who loves creating interactive web experiences. When I'm not coding, you can find me exploring new technologies, playing retro games, or contributing to open-source projects.</p>
                        <div class="tags" style="margin-top: 1rem;">
                            <span class="tag">JavaScript</span>
                            <span class="tag">Python</span>
                            <span class="tag">React</span>
                            <span class="tag">Node.js</span>
                            <span class="tag">Docker</span>
                        </div>
                    </div>
                </div>
            </section>

            <section id="skills" class="section">
                <h2>What I Do</h2>
                <div class="skills-grid">
                    <div class="skill-card">
                        <h3>Web Development</h3>
                        <p>Building responsive and performant web applications using modern frameworks and best practices.</p>
                    </div>
                    <div class="skill-card">
                        <h3>Game Development</h3>
                        <p>Creating engaging browser-based games like the classic Snake game you can try here!</p>
                    </div>
                    <div class="skill-card">
                        <h3>Cloud Solutions</h3>
                        <p>Deploying and managing applications using Docker, Kubernetes, and cloud platforms.</p>
                    </div>
                </div>
            </section>

            <section id="projects" class="section">
                <h2>Featured Projects</h2>
                <div class="projects-grid">
                    <article class="project-card">
                        <img src="/images/snake-game.jpg" alt="Snake Game" class="project-image">
                        <div class="project-content">
                            <h3>Snake Game</h3>
                            <p>A modern take on the classic Snake game, built with JavaScript and HTML5 Canvas.</p>
                            <a href="/modules/snake-game/" class="tag">Play Now</a>
                        </div>
                    </article>
                    <article class="project-card">
                        <img src="/images/news-feed.jpg" alt="News Feed" class="project-image">
                        <div class="project-content">
                            <h3>News Feed</h3>
                            <p>A personalized news aggregator that brings you the latest updates from various sources.</p>
                            <a href="/modules/news-feed/" class="tag">Check It Out</a>
                        </div>
                    </article>
                    <article class="project-card">
                        <img src="/images/portfolio.jpg" alt="Portfolio Website" class="project-image">
                        <div class="project-content">
                            <h3>This Website</h3>
                            <p>A responsive portfolio website built with modern CSS features and containerized with Docker.</p>
                            <span class="tag">Featured</span>
                        </div>
                    </article>
                </div>
            </section>

            <section id="contact" class="section">
                <h2>Get In Touch</h2>
                <div class="about-me" style="text-align: center;">
                    <p>Interested in collaborating or just want to say hi? Feel free to reach out!</p>
                    <div class="social-links">
                        <a href="https://github.com/" class="social-link" target="_blank">
                            <i class="fab fa-github"></i> GitHub
                        </a>
                        <a href="https://linkedin.com/" class="social-link" target="_blank">
                            <i class="fab fa-linkedin"></i> LinkedIn
                        </a>
                        <a href="mailto:contact@example.com" class="social-link">
                            <i class="fas fa-envelope"></i> Email
                        </a>
                    </div>
                </div>
            </section>
        </main>

        <footer>
            <p>&copy; 2025 John's Portfolio. Built with passion and coffee ☕</p>
            <div class="social-links">
                <a href="https://github.com/" class="social-link" target="_blank">
                    <i class="fab fa-github"></i>
                </a>
                <a href="https://linkedin.com/" class="social-link" target="_blank">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="mailto:contact@example.com" class="social-link">
                    <i class="fas fa-envelope"></i>
                </a>
            </div>
        </footer>
    </body>
    </html>